name: 🐞 Bug report 
description: File a bug report
labels: ["bug", "medium priority"]
assignees: ["sZeta99"]
body:
- type: checkboxes
  attributes:
    label: I have confirmed no other issue reports this bug
    description: Please search if an issue already exists for the bug you've encountered.
    options:
    - label: I have searched for existing issues
      required: true
- type: textarea
  attributes:
    label: Current behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. With this config...
      2. Enter a world...
      3. Do this...
      4. Bug happens...
- type: input
  attributes:
    label: Version
    description: |
      Version you're on.
    placeholder: |
      Version
  validations:
    required: true
- type: textarea
  attributes:
    label: Stacktrace and logs
    description: |
      Optionally paste here a link to [pastebin](https://pastebin.com/) with the crash/report/log.
    placeholder: |
      Logs or other usefull debug trace
- type: textarea
  attributes:
    label: Additional context
    description: |
      Insert here anything that will give us more context about the issue you are encountering.
